## SDGs Color Map
SDGS_COLOR_CODE = {
    '0':'#000000',
    '1':'#E5243B',
    '2':'#DDA63A',
    '3':'#4C9F38',
    '4':'#C5192D',
    '5':'#FF3A21',
    '6':'#26BDE2',
    '7':'#FCC30B',
    '8':'#A21942',
    '9':'#FD6925',
    '10':'#DD1367',
    '11':'#FD9D24',
    '12':'#BF8B2E',
    '13':'#3F7E44',
    '14':'#0A97D9',
    '15':'#56C02B',
    '16':'#00689D',
    '17':'#19486A',
}

SDG_GOAL_TEXT = [    
    {'code':'SDG01', 'Goal':'1', 'Goal_text':'No Poverty', 'indicator':'End poverty in all its forms everywhere'},
    {'code':'SDG02', 'Goal':'2', 'Goal_text':'Zero Hunger','indicator':'End hunger, achieve food security and improved nutrition and promote sustainable agriculture'},
    {'code':'SDG03', 'Goal':'3', 'Goal_text':'Good Health and Well-Being','indicator':'Ensure healthy lives and promote well-being for all at all ages'},
    {'code':'SDG04', 'Goal':'4', 'Goal_text':'Quality Education','indicator':'Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all'},
    {'code':'SDG05', 'Goal':'5', 'Goal_text':'Gender Equality','indicator':'Achieve gender equality and empower all women and girls'},
    {'code':'SDG06', 'Goal':'6', 'Goal_text':'Clean Water and Sanitation','indicator':'Ensure availability and sustainable management of water and sanitation for all'},
    {'code':'SDG07', 'Goal':'7', 'Goal_text':'Affordable and Clean Energy','indicator':'Ensure access to affordable, reliable, sustainable and modern energy for all'},
    {'code':'SDG08', 'Goal':'8', 'Goal_text':'Decent Work and Economic Growth','indicator':'Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all'},
    {'code':'SDG09', 'Goal':'9', 'Goal_text':'Industry, Innovation and Infrastructure','indicator':'Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation'},
    {'code':'SDG10', 'Goal':'10', 'Goal_text':'Reduced Inequalities','indicator':'Reduce inequality within and among countries'},
    {'code':'SDG11', 'Goal':'11', 'Goal_text':'Sustainable Cities and Communities','indicator':'Make cities and human settlements inclusive, safe, resilient and sustainable'},
    {'code':'SDG12', 'Goal':'12', 'Goal_text':'Responsible Consumption and Production','indicator':'Ensure sustainable consumption and production patterns'},
    {'code':'SDG13', 'Goal':'13', 'Goal_text':'Climate Action','indicator':'Take urgent action to combat climate change and its impacts'},
    {'code':'SDG14', 'Goal':'14', 'Goal_text':'Life Below Water','indicator':'Conserve and sustainably use the oceans, seas and marine resources for sustainable development'},
    {'code':'SDG15', 'Goal':'15', 'Goal_text':'Life on Land','indicator':'Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss'},
    {'code':'SDG16', 'Goal':'16', 'Goal_text':'Peace, Justice and Strong Institutions','indicator':'Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels'},
    {'code':'SDG17', 'Goal':'17', 'Goal_text':'Partnerships for the Goals','indicator':'Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development'},
]

WORLD_BANK_CUSTODIAN_INDICATORS = [
    'Indicator1-1-1',
    'Indicator1-2-1',
    'Indicator1-4-2',
    'Indicator3-8-2',
    'Indicator5-1-1',
    'Indicator7-1-1',
    'Indicator8-10-2',
    'Indicator9-1-1',
    'Indicator9-3-2',
    'Indicator10-1-1',
    'Indicator10-2-1',
    'Indicator10-4-2',
    'Indicator10-7-1',
    'Indicator10-c-1',
    'Indicator15-a-1',
    'Indicator15-b-1',
    'Indicator16-5-2',
    'Indicator16-6-1',
    'Indicator17-3-2',
    'Indicator17-4-1',
    'Indicator17-13-1',
    'Indicator17-17-1',
]

WORLD_BANK_INVOLVED_INDICATORS = [
    'Indicator1-2-2',
    'Indicator1-3-1',
    'Indicator2-3-2',
    'Indicator3-1-1',
    'Indicator3-2-1',
    'Indicator3-2-2',
    'Indicator4-2-1',
    'Indicator4-6-1',
    'Indicator5-5-1',
    'Indicator5-a-1',
    'Indicator5-a-2',
    'Indicator7-2-1',
    'Indicator7-3-1',
    'Indicator8-1-1',
    'Indicator8-2-1',
    'Indicator8-b-1',
    'Indicator9-2-1',
    'Indicator10-7-2',
    'Indicator16-10-2',
    'Indicator17-1-1',
    'Indicator17-18-3',
    'Indicator17-19-1',
]

CITY_COLOR_CODE = {
    "Taipei": "#C5AE96",
    "NewTaipei": "#FF8FA0",
    "Taoyuan": "#C6CFBF",
}

CITY_ABBR = {
    "Taipei": "TP",
    "NewTaipei": "NTP",
    "Taoyuan": "TY",
}